### PR TITLE
Simple graph with new algorithm

### LINKED ISSUE #7: Add highlighting of stack trace where a user has stopped on a breakpoint
Parallel Stacks highlight the stack trace where a user has stopped on a breakpoint. It looks like this:
Screenshot 2023-06-23 at 11 12 15

We need to add similar functionality to our plugin.

### LINKED ISSUE #8: Add capability to resolve to a source file when clicking on a frame
Parallel Stacks feature allows a user to resolve to a source location when clicking on a frame:
Monosnap screencast 2023-06-23 11-19-28

We need to add similar functionality to our plugin.

### PR DESCRIPTION
**Pull request by raehat**
Add capability to resolve to a source file when clicking on a frame
Add highlighting of stack trace where a user has stopped on a breakpoint

### CODE REVIEW

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 1]
```diff
@@ -31,34 +96,198 @@ class CoroutineStacksPanel(project: Project) : JBPanelWithEmptyText() {
...
-                insertEdge(parent, null, "", v1, v2)
-            } finally {
-                model.endUpdate()
-            }
+        val suspendContextImpl = suspendContext as? SuspendContextImpl ?: run {
+            emptyText.text = CoroutineStacksBundle.message("coroutine.stacks.could.not.be.built")
+            return
+        }
+
+        val positionManager = suspendContextImpl.debugProcess.positionManager
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: This variable is introduced a little too early, it is better to introduce it closer to use site

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 2]
```diff
@@ -1,23 +1,88 @@
...
+import java.awt.Component
+import java.awt.Font
+import java.awt.event.MouseAdapter
+import java.awt.event.MouseEvent
+import java.util.*
+import javax.swing.*
 
 class CoroutineStacksPanel(project: Project) : JBPanelWithEmptyText() {
-    private var coroutineGraph: JComponent? = null
+    private val coroutineGraph = Box.createVerticalBox()
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Maybe we should rename this variable now, since it contains not only the graph but also other UI elements. Maybe `panelContent` will do?

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 3]
```diff
@@ -31,34 +96,198 @@ class CoroutineStacksPanel(project: Project) : JBPanelWithEmptyText() {
...
+        coroutineGraph.add(coroutineStacksWindowHeader)
+        coroutineGraph.add(forest)
         add(coroutineGraph)
     }
-}
+
+    private fun updateCoroutineStackForest(
+        selectedDispatcher: String,
+        dispatcherToCoroutineDataList: MutableMap<String, MutableList<CoroutineInfoData>>,
+        positionManager: CompoundPositionManager
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: You can change the type to the interface type here: `positionManager: PositionManager`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 4]
```diff
@@ -31,34 +96,198 @@ class CoroutineStacksPanel(project: Project) : JBPanelWithEmptyText() {
...
+    ) {
+        forest.removeAll()
+        val root = Node(null, -1, mutableMapOf(), "")
+        val coroutineStackForest = buildCoroutineStackForest(
+            root,
+            dispatcherToCoroutineDataList[selectedDispatcher]!!,
+            positionManager
+        )
+        forest.add(coroutineStackForest)
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Discussed it in person: `updateUI()`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 5]
```diff
@@ -31,34 +96,198 @@ class CoroutineStacksPanel(project: Project) : JBPanelWithEmptyText() {
...
+    }
+
+    private fun buildCoroutineStackForest(
+        rootValue: Node,
+        coroutineDataList: MutableList<CoroutineInfoData>,
+        positionManager: CompoundPositionManager
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: `positionManager: PositionManager`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 6]
```diff
@@ -1,23 +1,88 @@
...
+import javax.swing.*
 
 class CoroutineStacksPanel(project: Project) : JBPanelWithEmptyText() {
-    private var coroutineGraph: JComponent? = null
+    private val coroutineGraph = Box.createVerticalBox()
+    private val forest = Box.createVerticalBox()
+
+    data class Node(
+        val stackFrameLocation: Location?,
+        var num: Int,
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Would be great to add a clarifying comment on what this number means to not forget this in the future

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 7]
```diff
@@ -31,34 +96,198 @@ class CoroutineStacksPanel(project: Project) : JBPanelWithEmptyText() {
...
+        forest.add(coroutineStackForest)
+    }
+
+    private fun buildCoroutineStackForest(
+        rootValue: Node,
+        coroutineDataList: MutableList<CoroutineInfoData>,
+        positionManager: CompoundPositionManager
+    ): JBScrollPane {
+        var lastRunningStackFrame = ""
+        coroutineDataList.forEach { coroutineData ->
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Let's extract this loop to a function, say `buildStackFrameGraph`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 8]
```diff
@@ -31,34 +96,198 @@ class CoroutineStacksPanel(project: Project) : JBPanelWithEmptyText() {
...
+                    )
+                    currentNode.children[location] = node
+                    currentNode = node
+                }
+            }
+        }
+
+        val locationMatrix: MutableList<MutableList<Location?>> = mutableListOf()
+        val stack = Stack<Pair<Node, Int>>()
+        val parentStack = Stack<Node>() // Stack to track parent nodes
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: This comment is a little superfluous and can be deleted

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 9]
```diff
@@ -31,34 +96,198 @@ class CoroutineStacksPanel(project: Project) : JBPanelWithEmptyText() {
...
+            locationMatrixWithSeparators.add(separator)
+        }
+
+        val componentData: MutableList<Component> = mutableListOf()
+        var headerIndex = 0
+        locationMatrixWithSeparators.forEachIndexed { i, separatorOrLocation ->
+            if (separatorOrLocation == separator) {
+                componentData.add(Separator())
+            } else {
+                val vertex = JBList<String>()
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Let's create a separate class to handle coroutine stacks UI, say `class CoroutineTrace : JBList<String>`, and handle  
all customisation there

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 10]
```diff
@@ -31,34 +96,198 @@ class CoroutineStacksPanel(project: Project) : JBPanelWithEmptyText() {
...
+
+        val separatorCount = locationMatrix.size - locationsFollowedBySeparators.size
+        repeat(separatorCount) {
+            locationMatrixWithSeparators.add(separator)
+        }
+
+        val componentData: MutableList<Component> = mutableListOf()
+        var headerIndex = 0
+        locationMatrixWithSeparators.forEachIndexed { i, separatorOrLocation ->
+            if (separatorOrLocation == separator) {
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Triple equals will be a little faster here `separatorOrLocation === separator`

**Review by nikita-nazarov — CHANGES_REQUESTED** [review]
Hi Raehat! Here are my comments, mostly minor. The code quality is very good!

**Comment by nikita-nazarov** [comment]
I also found out why there is a rendering bug with edges:

Screenshot 2023-06-27 at 11 46 17

ForestLayout implies that all of the components have equal width, but right now coroutine traces have different widths that depend on the length of a frame name. In ParallelStack components with stack traces have equal width, and when you navigate to a particular stack frame, it is expanded so you can see the full name:

Monosnap screencast 2023-06-27 11-51-45

Let's make the size of coroutine traces fixed and add the capability to expand frame names like in ParallelStacks!

**Comment by nikita-nazarov** [comment]
Also when you click on multiple frames, they stay highlighted:

Screenshot 2023-06-27 at 11 56 08

Let's fix this!

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 11]
```diff
@@ -1,23 +1,88 @@
...
+            } else {
+                (renderer as? JComponent)?.border = null
+            }
+
+            return renderer
+        }
+    }
+
+    fun performPositionTask(positionManager: PositionManager, location: Location) {
+        object : SwingWorker<SourcePosition?, Void>() {
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Occasionally when you click on stack frames you will get this exception:
```
java.lang.Throwable: Assertion failed: Should be invoked in manager thread, use DebuggerManagerThreadImpl.getInstance(..).invoke...
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:258)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.assertIsManagerThread(DebuggerManagerThreadImpl.java:55)
	at com.intellij.debugger.engine.DebugProcessImpl.getVirtualMachineProxy(DebugProcessImpl.java:821)
	at org.jetbrains.kotlin.idea.debugger.core.DebuggerUtil.visibleVariables(debuggerUtil.kt:124)
	at org.jetbrains.kotlin.idea.debugger.core.DebuggerUtil.isInsideInlineArgument(debuggerUtil.kt:70)
	at org.jetbrains.kotlin.idea.debugger.KotlinPositionManager.getLambdaOrFunStartingOrEndingOnLineIfInside(KotlinPositionManager.kt:292)
	at org.jetbrains.kotlin.idea.debugger.KotlinPositionManager.getSourcePosition(KotlinPositionManager.kt:150)
	at com.intellij.debugger.engine.CompoundPositionManager.lambda$getSourcePosition$2(CompoundPositionManager.java:109)
	at com.intellij.debugger.engine.CompoundPositionManager.lambda$iterate$0(CompoundPositionManager.java:84)
	at com.intellij.debugger.impl.DebuggerUtilsImpl.suppressExceptions(DebuggerUtilsImpl.java:248)
	at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:84)
	at com.intellij.debugger.engine.CompoundPositionManager.lambda$getSourcePosition$3(CompoundPositionManager.java:108)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:746)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:778)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:573)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$1(ProgressManager.java:70)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:107)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously(NonBlockingReadActionImpl.java:464)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.executeSynchronously(NonBlockingReadActionImpl.java:218)
	at com.intellij.debugger.engine.CompoundPositionManager.getSourcePosition(CompoundPositionManager.java:117)
	at com.nikitanazarov.coroutinestacks.CoroutineStacksPanel$performPositionTask$1.doInBackground(CoroutineStacksPanel.kt:74)
	at com.nikitanazarov.coroutinestacks.CoroutineStacksPanel$performPositionTask$1.doInBackground(CoroutineStacksPanel.kt:72)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
It happens because we should only use position manager in the debugger thread, so instead of running a SwingWorker we should do:
```
suspendContextImpl.debugProcess.managerThread.invoke(object : DebuggerCommandImpl() {
            override fun action() {
                val sourcePosition = positionManager.getSourcePosition(location)
                sourcePosition?.navigate(true)
            }
        })
```

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 12]
```diff
@@ -31,34 +96,198 @@ class CoroutineStacksPanel(project: Project) : JBPanelWithEmptyText() {
...
+        val stack = Stack<Pair<Node, Int>>()
+        val parentStack = Stack<Node>() // Stack to track parent nodes
+        val headerContent: MutableList<String> = mutableListOf()
+        val hoverContentForHeaders: MutableList<String?> = mutableListOf()
+
+        stack.push(Pair(rootValue, 0))
+        val locationsFollowedBySeparators = mutableListOf<Location?>()
+        var locationMatrixPointer = -1
+
+        while (stack.isNotEmpty()) {
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Let's extract this loop to a function as well

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 13]
```diff
@@ -31,34 +96,198 @@ class CoroutineStacksPanel(project: Project) : JBPanelWithEmptyText() {
...
+        }
+
+        val separatorCount = locationMatrix.size - locationsFollowedBySeparators.size
+        repeat(separatorCount) {
+            locationMatrixWithSeparators.add(separator)
+        }
+
+        val componentData: MutableList<Component> = mutableListOf()
+        var headerIndex = 0
+        locationMatrixWithSeparators.forEachIndexed { i, separatorOrLocation ->
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Let's extract ui fetching to a separate function

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 14]
```diff
@@ -31,34 +96,198 @@ class CoroutineStacksPanel(project: Project) : JBPanelWithEmptyText() {
...
+            if (locationsFollowedBySeparators.contains(locationData[0])) {
+                locationMatrixWithSeparators.add(separator)
+            }
+            locationMatrixWithSeparators.add(locationData)
+        }
+
+        val separatorCount = locationMatrix.size - locationsFollowedBySeparators.size
+        repeat(separatorCount) {
+            locationMatrixWithSeparators.add(separator)
+        }
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: I added capability to not add trailing separators to the tree-list, so you can delete this block of code once you rebase on the `forest-layout` branch

**Comment by nikita-nazarov** [comment]
Also by default we need to open the dispatcher that runs the coroutine that contains the breakpoint. Having to switch the dispatcher to find current stack trace can be a little misleading:

Monosnap screencast 2023-06-27 12-24-35

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 15]
```diff
@@ -1,64 +1,360 @@
...
 class CoroutineStacksPanel(project: Project) : JBPanelWithEmptyText() {
-    private var coroutineGraph: JComponent? = null
+    private val panelContent = Box.createVerticalBox()
+    private val forest = Box.createVerticalBox()
+
+    // num represents the number of times stackframe represented by respective Node occurs in the collection of all stack frames
+    // of all stack traces
+    data class Node(
+        val stackFrameLocation: Location?,
+        var num: Int,
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: `var num: Int, // Represents how many coroutines have this frame in their stack trace`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 16]
```diff
@@ -1,64 +1,360 @@
...
+        private val itemBorder = BorderFactory.createMatteBorder(0, 0, 1, 0, JBColor.GRAY)
+
+        override fun getListCellRendererComponent(
+            list: JList<*>,
+            value: Any,
+            index: Int,
+            isSelected: Boolean,
+            cellHasFocus: Boolean
+        ): Component {
+            val renderer = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus)
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Let's rewrite the function body like this:
```
            val renderer = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus)
            if (renderer !is JComponent) {
                return renderer
            }

            with(renderer) {
                val listSize = list.model.size
                if (index == 0) {
                    toolTipText = coroutinesActive
                    font = renderer.font.deriveFont(Font.BOLD)
                } else if (index < listSize) {
                    toolTipText = value.toString()
                }
                border = if (index < listSize - 1) itemBorder else null
            }

            return renderer

```

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 17]
```diff
@@ -1,64 +1,360 @@
...
+        }
+    }
 
     init {
-        layout = BorderLayout()
+        layout = BoxLayout(this, BoxLayout.Y_AXIS)
         emptyText.text = CoroutineStacksBundle.message("no.java.debug.process.is.running")
+        val currentSession = XDebuggerManager.getInstance(project).currentSession
+        if (currentSession != null) {
+            val myProcess = (currentSession.debugProcess as JavaDebugProcess).debuggerSession.process
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: `val currentProcess = (currentSession.debugProcess as? JavaDebugProcess)?.debuggerSession?.process`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 18]
```diff
@@ -1,64 +1,360 @@
...
-        with(graph) {
-            val parent = defaultParent
-            model.beginUpdate()
-            try {
-                val v1 = insertVertex(parent, null, "Hello,", 20.0, 20.0, 80.0, 30.0)
-                val v2 = insertVertex(parent, null, "World!", 200.0, 150.0, 80.0, 30.0)
-                insertEdge(parent, null, "", v1, v2)
-            } finally {
-                model.endUpdate()
+    private fun debugProcessListener() = object : DebugProcessListener {
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: `private fun createPanelBuilderListener()`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 19]
```diff
@@ -1,64 +1,360 @@
...
+        suspendContextImpl: SuspendContextImpl
+    ): JBList<String> {
+        val vertex = JBList<String>()
+        val data = mutableListOf<String>()
+        data.add(headerContent[headerIndex])
+        data.addAll(locationMatrixWithSeparators[i].map { it.toString() })
+        vertex.setListData(data.toTypedArray())
+        val lastStackFrame = data[locationMatrixWithSeparators[i].size]
+        vertex.border = if (lastRunningStackFrame == lastStackFrame) {
+            BorderFactory.createLineBorder(Color(5, 201, 255))
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: `JBColor`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 20]
```diff
@@ -1,64 +1,360 @@
...
+        } else {
+            BorderFactory.createLineBorder(Color.BLACK)
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: `JBColor`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 21]
```diff
@@ -1,64 +1,360 @@
...
+                    headerContent,
+                    headerIndex,
+                    locationMatrixWithSeparators,
+                    i,
+                    lastRunningStackFrame,
+                    hoverContentForHeaders,
+                    suspendContextImpl
+                )
+                vertex.addListSelectionListener { e ->
+                    val currentList = e.source as JBList<String>
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Lets rewrite the block this way:
```
                    val currentList = e.source as? JBList<*> ?: return@addListSelectionListener
                    if (previousListSelection != currentList) {
                        previousListSelection?.clearSelection()
                    }
                    previousListSelection = currentList

```

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 22]
```diff
@@ -1,64 +1,360 @@
...
+        }
+
+        val separatorCount = locationMatrix.size - locationsFollowedBySeparators.size
+        repeat(separatorCount) {
+            locationMatrixWithSeparators.add(separator)
+        }
+
+        val componentData: MutableList<Component> = mutableListOf()
+        var headerIndex = 0
+        var previousListSelection: JBList<String>? = null
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: `var previousListSelection: JBList<*>? = null`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 23]
```diff
@@ -1,64 +1,360 @@
...
+        val lastStackFrame = data[locationMatrixWithSeparators[i].size]
+        vertex.border = if (lastRunningStackFrame == lastStackFrame) {
+            BorderFactory.createLineBorder(Color(5, 201, 255))
+        } else {
+            BorderFactory.createLineBorder(Color.BLACK)
+        }
+        vertex.cellRenderer = CustomCellRenderer(hoverContentForHeaders[headerIndex])
+        vertex.addMouseListener(object : MouseAdapter() {
+            override fun mouseClicked(e: MouseEvent?) {
+                val list = e?.source as JBList<*>
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: ` val list = e?.source as? JBList<*> ?: return`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 24]
```diff
@@ -1,64 +1,360 @@
...
+                val index = list.locationToIndex(e.point)
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]:
```
val index = list.locationToIndex(e.point).takeIf { it > 0 } ?: return
val location = locationMatrixWithSeparators[i][index - 1] ?: return
```

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 25]
```diff
@@ -1,64 +1,360 @@
...
+                }
+                stack.push(child to (level + 1))
+                parentStack.push(currentNode)
             }
         }
+    }
 
-        coroutineGraph = mxGraphComponent(graph)
-        add(coroutineGraph)
+    private fun createCoroutineTrace(
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Let's extract the UI creation logic to a separate class as we've discussed recently!

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 26]
```diff
@@ -1,64 +1,360 @@
...
+            headerContent,
+            hoverContentForHeaders,
+            locationMatrix,
+            locationsFollowedBySeparators
+        )
+
+        val separator : MutableList<Location?> = mutableListOf(null)
+        val locationMatrixWithSeparators: MutableList<MutableList<Location?>> = mutableListOf()
+        for (locationData in locationMatrix) {
+            if (locationsFollowedBySeparators.contains(locationData[0])) {
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: What if locationData is empty?

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 27]
```diff
@@ -1,64 +1,360 @@
...
+                locationMatrixWithSeparators.add(separator)
+            }
+            locationMatrixWithSeparators.add(locationData)
+        }
+
+        val separatorCount = locationMatrix.size - locationsFollowedBySeparators.size
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: If you rebase on the fresh version of the `forest-layout` branch, you can delete this block

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 28]
```diff
@@ -1,64 +1,360 @@
...
+        updateUI()
+    }
+
+    private fun buildCoroutineStackForest(
+        rootValue: Node,
+        coroutineDataList: MutableList<CoroutineInfoData>,
+        suspendContextImpl: SuspendContextImpl
+    ): JBScrollPane {
+        var lastRunningStackFrame = ""
+        lastRunningStackFrame = buildStackFrameGraph(coroutineDataList, rootValue, lastRunningStackFrame)
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: `val lastRunningStackFrame = buildStackFrameGraph(coroutineDataList, rootValue)`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 29]
```diff
@@ -1,64 +1,360 @@
...
+        repeat(separatorCount) {
+            locationMatrixWithSeparators.add(separator)
+        }
+
+        val componentData: MutableList<Component> = mutableListOf()
+        var headerIndex = 0
+        var previousListSelection: JBList<String>? = null
+        locationMatrixWithSeparators.forEachIndexed { i, separatorOrLocation ->
+            if (separatorOrLocation === separator) {
+                componentData.add(Separator())
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]:
```
componentData.add(Separator())
return@forEachIndexed
```

And you won't need the `else` block

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 30]
```diff
@@ -1,64 +1,360 @@
...
+        val coroutineStackForest = buildCoroutineStackForest(
+            root,
+            dispatcherToCoroutineDataList[selectedDispatcher]!!,
+            suspendContextImpl
+        )
+        forest.add(coroutineStackForest)
+        updateUI()
+    }
+
+    private fun buildCoroutineStackForest(
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Speaking about this function, it is very hard to read it. We have 3 stages in the forest building algorithm:
1. Stack frame graph building
2. Creating a forest of coroutine traces
3. Creating UI

However, I can't see these stages while reading this function, which makes it extremely hard to understand and maintain. I made a sketch of how it should ideally look like:
```
    data class CoroutineTrace(val locations: MutableList<Location>, val header: String, val hoverContent: String)
    
    private fun SuspendContextImpl.buildCoroutineStackForest(
        rootValue: Node,
        coroutineDataList: MutableList<CoroutineInfoData>,
    ): JBScrollPane {
        val lastRunningStackFrame = buildStackFrameGraph(coroutineDataList, rootValue)
        val coroutineTraces = createCoroutineTraces(rootValue)
        return createCoroutineTraceForest(coroutineTraces, lastRunningStackFrame)
    }

    private fun SuspendContextImpl.createCoroutineTraceForest(traces: List<CoroutineTrace?>, lastRunningStackFrame: String): JBScrollPane {
        val componentData: MutableList<Component> = mutableListOf()
        var previousListSelection: JBList<*>? = null
        traces.forEach { trace ->
            if (trace == null) {
                componentData.add(Separator())
                return@forEach
            }
            val vertex = createCoroutineTraceUI(trace, lastRunningStackFrame)
            vertex.addListSelectionListener { e ->
                val currentList = e.source as? JBList<*> ?: return@addListSelectionListener
                if (previousListSelection != currentList) {
                    previousListSelection?.clearSelection()
                }
                previousListSelection = currentList
            }
            componentData.add(vertex)
        }

        val forest = ContainerWithEdges()
        componentData.forEach { forest.add(it) }
        forest.layout = ForestLayout()
        return JBScrollPane(forest)
    }

    private fun createCoroutineTraces(rootValue: Node): List<CoroutineTrace?> {
        val stack = Stack<Pair<Node, Int>>()
        val parentStack = Stack<Node>()

        stack.push(Pair(rootValue, 0))
        val locationsFollowedBySeparators = mutableListOf<Location?>()

        var currentTrace: CoroutineTrace? = null
        val coroutineTraces = mutableListOf<CoroutineTrace?>()
        while (stack.isNotEmpty()) {
            val (currentNode, level) = stack.pop()
            val parent = if (parentStack.isNotEmpty()) parentStack.pop() else null

            if (parent != null) {
                if (parent.num != currentNode.num) {
                    currentTrace = CoroutineTrace(
                        mutableListOf(currentNode.stackFrameLocation),
                        "${currentNode.num} Coroutines ACTIVE",
                        currentNode.coroutinesActive
                    )
                    coroutineTraces.add(currentTrace)
                } else {
                    currentTrace?.locations?.add(currentNode.stackFrameLocation)
                }
            }

            currentNode.children.values.reversed().forEachIndexed { index, child ->
                if (index != currentNode.children.values.size - 1) {
                    locationsFollowedBySeparators.add(child.stackFrameLocation)
                    coroutineTraces.add(null)
                }
                stack.push(child to (level + 1))
                parentStack.push(currentNode)
            }
        }

        return coroutineTraces
    }

    private fun SuspendContextImpl.createCoroutineTraceUI(trace: CoroutineTrace, lastRunningStackFrame: String): JBList<String> {
        val vertex = JBList<String>()
        val data = mutableListOf<String>()
        data.add(trace.header)
        data.addAll(trace.locations.map { it.toString() })
        vertex.setListData(data.toTypedArray())
        val lastStackFrame = data[trace.locations.size]
        vertex.border = if (lastRunningStackFrame == lastStackFrame) {
            BorderFactory.createLineBorder(JBColor.GRAY)
        } else {
            BorderFactory.createLineBorder(JBColor.BLACK)
        }
        vertex.cellRenderer = CustomCellRenderer(trace.hoverContent)
        vertex.addMouseListener(object : MouseAdapter() {
            override fun mouseClicked(e: MouseEvent?) {
                val list = e?.source as? JBList<*> ?: return
                val index = list.locationToIndex(e.point).takeIf { it > 0 } ?: return
                val location = trace.locations[index - 1]
                debugProcess.managerThread.invoke(object : DebuggerCommandImpl() {
                    override fun action() {
                        val positionManager = debugProcess.positionManager
                        val sourcePosition = positionManager.getSourcePosition(location)
                        sourcePosition?.navigate(true)
                    }
                })
            }
        })

        return vertex
    }

```

So now the `buildCoroutineStackForest` function looks like this:
```
private fun SuspendContextImpl.buildCoroutineStackForest(
        rootValue: Node,
        coroutineDataList: MutableList<CoroutineInfoData>,
    ): JBScrollPane {
        val lastRunningStackFrame = buildStackFrameGraph(coroutineDataList, rootValue)
        val coroutineTraces = createCoroutineTraces(rootValue)
        return createCoroutineTraceForest(coroutineTraces, lastRunningStackFrame)
    }
```
It is just 3 lines long, but we can clearly see what is going on.

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 31]
```diff
@@ -1,64 +1,360 @@
...
+                }
+            }
+        })
+        return vertex
+    }
+
+    private fun buildStackFrameGraph(
+        coroutineDataList: MutableList<CoroutineInfoData>,
+        rootValue: Node,
+        lastRunningStackFrame: String
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: You don't need this parameter here, as it is always an empty string

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 32]
```diff
@@ -1,64 +1,360 @@
...
+    ): String {
+        var lastRunningStackFrame1 = lastRunningStackFrame
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: `var lastRunningStackFrame = ""`

**Review by nikita-nazarov — CHANGES_REQUESTED** [review]

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 33]
```diff
@@ -1,64 +1,386 @@
...
+        var coroutinesActive: String = ""
+    )
+
+    class CustomCellRenderer(
+        private val coroutinesActive: String?,
+        private val averagePreferredWidth: Int,
+        padding: Int = 3
+    ) : DefaultListCellRenderer() {
+        private val itemBorder = BorderFactory.createMatteBorder(0, 0, 1, 0, JBColor.GRAY)
+        private val leftPaddingBorder: Border = EmptyBorder(0, padding, 0, 0)
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Use `JBUI.Borders.emptyLeft(padding)` instead

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 34]
```diff
@@ -1,64 +1,386 @@
...
-            } finally {
-                model.endUpdate()
+    private fun createRoundedBorder(color: JBColor): Border {
+        val cornerRadius = 10
+        val borderThickness = 1
+
+        val roundedBorder = object : LineBorder(color, borderThickness) {
+            override fun getBorderInsets(c: Component?): Insets {
+                val insets = super.getBorderInsets(c)
+                return Insets(insets.top, insets.left, insets.bottom, insets.right)
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: `JBUI.insets(insets.top, insets.left, insets.bottom, insets.right)`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 35]
```diff
@@ -1,64 +1,386 @@
...
-            val parent = defaultParent
-            model.beginUpdate()
-            try {
-                val v1 = insertVertex(parent, null, "Hello,", 20.0, 20.0, 80.0, 30.0)
-                val v2 = insertVertex(parent, null, "World!", 200.0, 150.0, 80.0, 30.0)
-                insertEdge(parent, null, "", v1, v2)
-            } finally {
-                model.endUpdate()
+    private fun createRoundedBorder(color: JBColor): Border {
+        val cornerRadius = 10
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Let's extract it to `Constants.kt`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 36]
```diff
@@ -1,64 +1,386 @@
...
+        val borderThickness = 1
+
+        val roundedBorder = object : LineBorder(color, borderThickness) {
+            override fun getBorderInsets(c: Component?): Insets {
+                val insets = super.getBorderInsets(c)
+                return Insets(insets.top, insets.left, insets.bottom, insets.right)
+            }
+
+            override fun paintBorder(c: Component?, g: Graphics?, x: Int, y: Int, width: Int, height: Int) {
+                val g2d = g as? Graphics2D
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]:
```
val g2d = g as? Graphics2D ?: return
val arc = 2 * cornerRadius
g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON)
g2d.color = color
g2d.drawRoundRect(x, y, width - 1, height - 1, arc, arc)
```

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 37]
```diff
@@ -1,64 +1,386 @@
...
+                val location = stackFrame.location
+                val child = currentNode.children[location]
+
+                if (child != null) {
+                    if (coroutineData.descriptor.state == State.RUNNING) {
+                        lastRunningStackFrame = child.stackFrameLocation.toString()
+                    }
+
+                    child.num++
+                    child.coroutinesActive += "${coroutineData.descriptor.name}${coroutineData.descriptor.id} ${coroutineData.descriptor.state}\n"
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]:
```
private fun CoroutineInfoData.render(): String =
    "${descriptor.name}${descriptor.id} ${descriptor.state}\n"
```

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 38]
```diff
@@ -1,64 +1,386 @@
...
+
+        return coroutineTraces
+    }
+
+    private fun SuspendContextImpl.createCoroutineTraceUI(
+        trace: CoroutineTrace,
+        lastRunningStackFrame: String,
+        averagePreferredWidth: Int
+    ): JBList<String> {
+        val (vertex, data) = createVertexAndData(trace)
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: We can inline `createVertexAndData` function here:
```
val vertex = JBList<String>()
val data = mutableListOf<String>()
data.add(trace.header)
data.addAll(trace.locations.map { it.toString() })
vertex.setListData(data.toTypedArray())
vertex.border = if (lastRunningStackFrame == trace.locations.firstOrNull()?.toString()) {
    createRoundedBorder(JBColor.BLUE)
} else {
    createRoundedBorder(JBColor.BLACK)
}

vertex.cellRenderer = CustomCellRenderer(trace.hoverContent, averagePreferredWidth)
vertex.addMouseListener(object : MouseAdapter() {
    override fun mouseClicked(e: MouseEvent?) {
        val list = e?.source as? JBList<*> ?: return
        val index = list.locationToIndex(e.point).takeIf { it > 0 } ?: return
        val location = trace.locations[index - 1]
        debugProcess.managerThread.invoke(object : DebuggerCommandImpl() {
            override fun action() {
                val positionManager = debugProcess.positionManager
                val sourcePosition = positionManager.getSourcePosition(location)
                sourcePosition?.navigate(true)
            }
        })
    }
})

return vertex
```

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 39]
```diff
@@ -1,64 +1,386 @@
...
+    ): JBScrollPane {
+        val lastRunningStackFrame = buildStackFrameGraph(coroutineDataList, rootValue)
+        val coroutineTraces = createCoroutineTraces(rootValue)
+        return createCoroutineTraceForest(coroutineTraces, lastRunningStackFrame)
+    }
+
+    private fun SuspendContextImpl.createCoroutineTraceForest(traces: List<CoroutineTrace?>, lastRunningStackFrame: String): JBScrollPane {
+        val componentData: MutableList<Component> = mutableListOf()
+        var previousListSelection: JBList<*>? = null
+        val averagePreferredWidth = calculateAveragePreferredWidth(traces)
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Creating all stack traces just to calculate the average width is very expensive, let's calculate necessary components such as sum of widths and vertices number while we are creating vertices from coroutine traces

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 40]
```diff
@@ -1,64 +1,386 @@
...
+import javax.swing.border.Border
+import javax.swing.border.EmptyBorder
+import javax.swing.border.LineBorder
 
 class CoroutineStacksPanel(project: Project) : JBPanelWithEmptyText() {
-    private var coroutineGraph: JComponent? = null
+    private val panelContent = Box.createVerticalBox()
+    private val forest = Box.createVerticalBox()
+
+    data class CoroutineTrace(val locations: MutableList<Location?>, val header: String, val hoverContent: String)
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Maybe instead of `hoverContent` we can call it `coroutinesActiveLabel`?

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 41]
```diff
@@ -1,64 +1,386 @@
...
+
+    data class Node(
+        val stackFrameLocation: Location? = null,
+        var num: Int = 0, // Represents how many coroutines have this frame in their stack trace
+        val children: MutableMap<Location, Node> = mutableMapOf(),
+        var coroutinesActive: String = ""
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: `coroutinesActiveLabel`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 42]
```diff
@@ -1,64 +1,386 @@
...
+    )
+
+    class CustomCellRenderer(
+        private val coroutinesActive: String?,
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: `coroutinesActiveLabel`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt (hunk 40 above)
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Let's extract all coroutine trace forest building logic to a separate file:
```
data class CoroutineTrace ...

data class Node ...

object CoroutineTraceForestBuilder {
    fun buildCoroutineStackForest ...
    private fun buildStackFrameGraph ...
    private fun createCoroutineTraces ...
}

```

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 43]
```diff
@@ -1,64 +1,386 @@
...
+            currentNode.children.values.reversed().forEach { child ->
+                stack.push(child to (currentLevel + 1))
+                parentStack.push(currentNode)
+            }
+        }
+
+        return coroutineTraces
+    }
+
+    private fun SuspendContextImpl.createCoroutineTraceUI(
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: It would be better extract the coroutine trace UI to a separate class and handle all customisation there:

```
class CoroutineFramesList : JBList<String> {
 ...
}
```

**Review by nikita-nazarov — CHANGES_REQUESTED** [review]

**Comment by nikita-nazarov** [comment]
I also found a bug when multiple traces are highlighted:

Screenshot 2023-07-08 at 00 27 29

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 44]
```diff
@@ -1,64 +1,386 @@
...
+            dispatcherToCoroutineDataList.computeIfAbsent(dispatcher) { mutableListOf() }.add(info)
+        }
+
+        val dispatcherLabel = JLabel(CoroutineStacksBundle.message("select.dispatcher"))
+        val coroutineStacksWindowHeader = Box.createHorizontalBox()
+        val dispatchers = dispatcherToCoroutineDataList.keys.toTypedArray()
+        val dispatcherDropdownMenu = ComboBox(dispatchers)
+
+        dispatcherDropdownMenu.addActionListener {
+            val selectedDispatcher = dispatcherDropdownMenu.selectedItem as String
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: `as? String`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 45]
```diff
@@ -1,64 +1,386 @@
...
+
+        dispatcherToCoroutineDataList.forEach { (dispatcher, coroutineDataList) ->
+            coroutineDataList.forEach { data ->
+                if (data.descriptor.state == State.RUNNING) {
+                    dispatcherDropdownMenu.selectedItem = dispatcher
+                }
+            }
+        }
+
+        val selectedDispatcher = dispatcherDropdownMenu.selectedItem as String
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: `as? String`

**Comment by nikita-nazarov** [comment]
Also sometimes I got this exception as amount of Separators was too large:
```
java.lang.ArrayIndexOutOfBoundsException: No such child: -1
	at java.desktop/java.awt.Container.getComponent(Container.java:354)
	at com.nikitanazarov.coroutinestacks.ui.ForestLayout.getComponentSize(ForestLayout.kt:109)
	at com.nikitanazarov.coroutinestacks.ui.ForestLayout.access$getComponentSize(ForestLayout.kt:9)
	at com.nikitanazarov.coroutinestacks.ui.ForestLayout$preferredLayoutSize$1.leaveComponent(ForestLayout.kt:34)
	at com.nikitanazarov.coroutinestacks.ui.ForestLayoutKt.dfs$leaveComponent(ForestLayout.kt:137)
	at com.nikitanazarov.coroutinestacks.ui.ForestLayoutKt.dfs(ForestLayout.kt:149)
	at com.nikitanazarov.coroutinestacks.ui.ForestLayout.preferredLayoutSize(ForestLayout.kt:20)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1826)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at com.intellij.ui.components.JBViewport.getPreferredScrollableViewportSize(JBViewport.java:519)
	at com.intellij.ui.components.JBViewport$1.preferredLayoutSize(JBViewport.java:65)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1826)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1723)
	at com.intellij.ui.components.JBScrollPane$Layout.preferredLayoutSize(JBScrollPane.java:820)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1826)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1723)
	at java.desktop/javax.swing.BoxLayout.checkRequests(BoxLayout.java:476)
	at java.desktop/javax.swing.BoxLayout.minimumLayoutSize(BoxLayout.java:318)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at java.desktop/javax.swing.BoxLayout.checkRequests(BoxLayout.java:475)
	at java.desktop/javax.swing.BoxLayout.minimumLayoutSize(BoxLayout.java:318)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at java.desktop/javax.swing.BoxLayout.checkRequests(BoxLayout.java:475)
	at java.desktop/javax.swing.BoxLayout.layoutContainer(BoxLayout.java:417)
	at java.desktop/java.awt.Container.layout(Container.java:1541)
	at java.desktop/java.awt.Container.doLayout(Container.java:1530)
	at java.desktop/java.awt.Container.validateTree(Container.java:1725)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validate(Container.java:1660)
	at com.intellij.toolWindow.ToolWindowPane.removeDecorator(ToolWindowPane.kt:220)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.removeDecoratorWithoutUpdatingState(ToolWindowManagerImpl.kt:1176)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.updateStateAndRemoveDecorator(ToolWindowManagerImpl.kt:1158)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.deactivateToolWindow(ToolWindowManagerImpl.kt:695)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.executeHide(ToolWindowManagerImpl.kt:855)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.hideToolWindow(ToolWindowManagerImpl.kt:836)
	at com.jetbrains.rdserver.toolWindow.BackendServerToolWindowManager.hideToolWindow(BackendServerToolWindowManager.kt:215)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.hideToolWindow$default(ToolWindowManagerImpl.kt:813)
	at com.intellij.toolWindow.InternalDecoratorImpl$1.hideToolWindow(InternalDecoratorImpl.kt:166)
	at com.intellij.toolWindow.ToolWindowHeader$HideAction.actionPerformed(ToolWindowHeader.kt:435)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:228)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$2(ActionButton.java:207)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:207)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:518)
	at java.desktop/java.awt.Component.processEvent(Component.java:6421)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2804)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:790)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:763)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:761)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:615)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

You need to check the number of separators that are added. I assume there is something wrong in `com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt:288`

**Comment by nikita-nazarov** [comment]
I've also added a commit that fixes the rendering issue, so please rebase on the `forest-layout` branch.

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt (hunk 44 above)
Comment (nikita-nazarov) [reply src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: This comment is still pending

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt (hunk 45 above)
Comment (nikita-nazarov) [reply src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: This comment is still pending

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt [hunk 46]
```diff
@@ -0,0 +1,258 @@
...
+        currentNode.children.values.reversed().forEach { child ->
+            stack.push(child to (currentLevel + 1))
+            parentStack.push(currentNode)
+        }
+    }
+
+    return coroutineTraces
+}
+
+private class CoroutineTraceUI(
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt]: I think it would be better to rewrite this class like:
```
private class CoroutineFramesList(
    suspendContext: SuspendContextImpl,
    trace: CoroutineTrace,
    lastRunningStackFrame: String
) : JBList<String>() {
    init {
        val debugProcess = suspendContext.debugProcess
        val activeExecutionStack = suspendContext.activeExecutionStack

        val data = mutableListOf<String>()
        data.add(trace.header)
        data.addAll(trace.stackFrameItems.map { it.toString() })
        setListData(data.toTypedArray())
        val lastStackFrame = data.getOrNull(1)

        border = if (lastRunningStackFrame == lastStackFrame) {
            createRoundedBorder(JBColor.BLUE)
        } else {
            createRoundedBorder(JBColor.BLACK)
        }

        cellRenderer = CoroutineStacksPanel.CustomCellRenderer(trace.coroutinesActiveLabel)
        addMouseListener(object : MouseAdapter() {
            override fun mouseClicked(e: MouseEvent?) {
                val list = e?.source as? JBList<*> ?: return
                val index = list.locationToIndex(e.point).takeIf { it > 0 } ?: return
                val stackFrameItem = trace.stackFrameItems[index - 1]

                stackFrameItem?.let { frameItem ->
                    val frame = frameItem.createFrame(debugProcess)

                    if (activeExecutionStack != null && frame != null) {
                        suspendContext.setCurrentStackFrame(activeExecutionStack, frame)
                    }
                }
            }
        })
    }
}
```

Comment (nikita-nazarov) [reply src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt]: And also let's move it to a separate file! Together with `createRoundedBorder` and  `CustomCellRenderer`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt [hunk 47]
```diff
@@ -0,0 +1,258 @@
...
+import javax.swing.border.LineBorder
+
+data class Node(
+    val stackFrameItem: CoroutineStackFrameItem? = null,
+    var num: Int = 0, // Represents how many coroutines have this frame in their stack trace
+    val children: MutableMap<Location, Node> = mutableMapOf(),
+    var coroutinesActive: String = ""
+)
+
+data class CoroutineTrace(val stackFrameItems: MutableList<CoroutineStackFrameItem?>, val header: String, val coroutinesActiveLabel: String)
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt]: This line is too long, let's move the declarations to separate lines

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt [hunk 48]
```diff
@@ -0,0 +1,258 @@
...
+
+private fun CoroutineInfoData.render(): String =
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt]: Let's put this function in the bottom of the file, since it is private anyway and doesn't expose any interesting api, and is used only for internal implementation of this file

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt [hunk 49]
```diff
@@ -0,0 +1,258 @@
...
+    val lastRunningStackFrame = buildStackFrameGraph(coroutineDataList, rootValue)
+    val coroutineTraces = createCoroutineTraces(rootValue)
+    return createCoroutineTraceForest(coroutineTraces, lastRunningStackFrame)
+}
+
+private fun SuspendContextImpl.createCoroutineTraceForest(
+    traces: List<CoroutineTrace?>,
+    lastRunningStackFrame: String
+): JBScrollPane? {
+    if (traces.isEmpty()) return null
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt]: Let's do it like this:
```
if (traces.isEmpty()) {
  return null
}
```

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt [hunk 50]
```diff
@@ -0,0 +1,258 @@
...
+    val vertexData: MutableList<JBList<String>?> = mutableListOf()
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt]: `    val vertexData = mutableListOf<JBList<String>?>()`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt [hunk 51]
```diff
@@ -0,0 +1,258 @@
...
+    val componentData: MutableList<Component> = mutableListOf()
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt]: `    val componentData = mutableListOf<Component>()`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt [hunk 52]
```diff
@@ -0,0 +1,258 @@
...
+                previousListSelection?.clearSelection()
+            }
+            previousListSelection = currentList
+        }
+        vertexData.add(vertex)
+        maxWidth += vertex.preferredWidth
+        traceNotNullCount += 1
+    }
+
+    val averagePreferredWidth = maxWidth / traceNotNullCount
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt:75]: what if `traceNotNullCount` is zero?

Comment (nikita-nazarov) [reply src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt:75]: This can only happen if the `traces` list is ill-formed and only contains nulls, but we have to check for this situation anyway for our code to be safe

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt [hunk 53]
```diff
@@ -0,0 +1,258 @@
...
+        if (vertex != null) {
+            vertex.preferredWidth = averagePreferredWidth
+            componentData.add(vertex)
+            return@forEach
+        }
+        componentData.add(Separator())
+    }
+
+    val forest = ContainerWithEdges()
+    componentData.forEach { forest.add(it) }
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt:86]: Let's move this line to the constructor of `ContainerWithEdges`.  After that we will be able to write:
```
val forest =  ContainerWithEdges(componentData).apply {
      layout = ForestLayout()
}
```

Comment (nikita-nazarov) [reply src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt:86]: Also try using the DraggablePanel from the fresh version of the `forest-layout` branch!

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt [hunk 54]
```diff
@@ -0,0 +1,258 @@
...
+                    if (activeExecutionStack != null && frame != null) {
+                        suspendContextImpl.setCurrentStackFrame(activeExecutionStack, frame)
+                    }
+                }
+            }
+        })
+    }
+}
+
+private fun SuspendContextImpl.setCurrentStackFrame(executionStack: XExecutionStack?, stackFrame: XStackFrame) {
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt]: Let's add a coment `// Copied from org.jetbrains.kotlin.idea.debugger.coroutine.view.CoroutineSelectedNodeListener#setCurrentStackFrame`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt [hunk 55]
```diff
@@ -0,0 +1,258 @@
...
+                    1,
+                    mutableMapOf(),
+                    coroutineData.render()
+                )
+                currentNode.children[location] = node
+                currentNode = node
+            }
+        }
+    }
+    return lastRunningStackFrame
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt]: Lets add a blank line before return

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 56]
```diff
@@ -1,64 +1,179 @@
...
+        coroutineDataList: MutableList<CoroutineInfoData>,
+        suspendContextImpl: SuspendContextImpl
+    ) {
+        forest.removeAll()
+        val root = Node()
+        val coroutineStackForest = suspendContextImpl.buildCoroutineStackForest(
+            root,
+            coroutineDataList
+        ) ?: run {
+            emptyText.text = CoroutineStacksBundle.message("nothing.to.show")
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: It looks like you forgot to add the message to the bundle

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 57]
```diff
@@ -1,64 +1,179 @@
...
+    }
+
 
     init {
-        layout = BorderLayout()
+        layout = BoxLayout(this, BoxLayout.Y_AXIS)
         emptyText.text = CoroutineStacksBundle.message("no.java.debug.process.is.running")
+        val currentSession = XDebuggerManager.getInstance(project).currentSession
+        if (currentSession != null) {
+            val currentProcess = (currentSession.debugProcess as JavaDebugProcess).debuggerSession.process
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: `as? JavaDebugProcess`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 58]
```diff
@@ -1,64 +1,179 @@
...
-        with(graph) {
-            val parent = defaultParent
-            model.beginUpdate()
-            try {
-                val v1 = insertVertex(parent, null, "Hello,", 20.0, 20.0, 80.0, 30.0)
-                val v2 = insertVertex(parent, null, "World!", 200.0, 150.0, 80.0, 30.0)
-                insertEdge(parent, null, "", v1, v2)
-            } finally {
-                model.endUpdate()
+    private fun createPanelBuilderListener() = object : DebugProcessListener {
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: `val panelBuilderListener = object : DebugProcessListener ...`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 59]
```diff
@@ -1,64 +1,179 @@
...
+        add(panelContent)
+    }
+
+    private fun updateCoroutineStackForest(
+        coroutineDataList: MutableList<CoroutineInfoData>,
+        suspendContextImpl: SuspendContextImpl
+    ) {
+        forest.removeAll()
+        val root = Node()
+        val coroutineStackForest = suspendContextImpl.buildCoroutineStackForest(
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: We need to wrap the stack forest building logic in the debugger thread, and the UI building logic in the UI thread

**Review by nikita-nazarov — CHANGES_REQUESTED** [review]

File: src/main/resources/messages/CoroutineStacksBundle.properties [hunk 60]
```diff
@@ -1,2 +1,5 @@
 no.java.debug.process.is.running=No Java debug process is currently running
 should.be.stopped.on.a.breakpoint=The debug process should be stopped on a breakpoint
+coroutine.stacks.could.not.be.built=Coroutine Stacks could not be built
+select.dispatcher=Select Dispatcher:  
+number.of.coroutines.active={0} Coroutines Active
```
Comment (nikita-nazarov) [inline src/main/resources/messages/CoroutineStacksBundle.properties:5]: Let's omit the `Active` word. We also need to add proper ending for examples like: 1 Coroutine, 2 Coroutine**s**

Comment (nikita-nazarov) [inline src/main/resources/messages/CoroutineStacksBundle.properties]: Let's omit the `Active` word. We also need to add proper ending for examples like: 1 Coroutine, 2 Coroutine**s**

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineFramesList.kt [hunk 61]
```diff
@@ -0,0 +1,133 @@
...
+import java.awt.event.MouseAdapter
+import java.awt.event.MouseEvent
+import javax.swing.BorderFactory
+import javax.swing.DefaultListCellRenderer
+import javax.swing.JComponent
+import javax.swing.JList
+import javax.swing.border.Border
+import javax.swing.border.LineBorder
+
+class CoroutineFramesList(
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineFramesList.kt]: Let's move this file to the `ui` package

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineFramesList.kt [hunk 62]
```diff
@@ -0,0 +1,133 @@
...
+                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON)
+                g2d.color = color
+                g2d.drawRoundRect(x, y, width - 1, height - 1, arc, arc)
+            }
+        }
+
+        return roundedBorder
+    }
+
+    class CustomCellRenderer(
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineFramesList.kt]: This class is only used in one place, so let's make it an anonymous object instead

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineFramesList.kt [hunk 63]
```diff
@@ -0,0 +1,133 @@
...
+        private val coroutinesActive: String?,
+        padding: Int = 3
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineFramesList.kt]: The padding is always equal to 3, se let's remove this argument

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineFramesList.kt [hunk 64]
```diff
@@ -0,0 +1,133 @@
...
+    ) : DefaultListCellRenderer() {
+        private val itemBorder = BorderFactory.createMatteBorder(0, 0, 1, 0, JBColor.GRAY)
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineFramesList.kt]: these 3 variables clearly belong to a companion object in the CoroutineFramesListClass

File: src/main/resources/messages/CoroutineStacksBundle.properties [hunk 65]
```diff
@@ -2,4 +2,6 @@ no.java.debug.process.is.running=No Java debug process is currently running
 should.be.stopped.on.a.breakpoint=The debug process should be stopped on a breakpoint
 coroutine.stacks.could.not.be.built=Coroutine Stacks could not be built
 select.dispatcher=Select Dispatcher:  
-number.of.coroutines.active={0} Coroutines Active
\ No newline at end of file
+number.of.coroutine=1 Coroutine
+number.of.coroutines={0} Coroutines
+nothing.to.show=No Coroutine StackTrace available for display
```
Comment (nikita-nazarov) [inline src/main/resources/messages/CoroutineStacksBundle.properties]: `No stack traces are available for display`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt [hunk 66]
```diff
@@ -102,11 +99,14 @@ private fun createCoroutineTraces(rootValue: Node): List<CoroutineTrace?> {
     while (stack.isNotEmpty()) {
         val (currentNode, currentLevel) = stack.pop()
         val parent = if (parentStack.isNotEmpty()) parentStack.pop() else null
+        var coroutineStackHeader = CoroutineStacksBundle.message("number.of.coroutine")
 
         if (parent != null && parent.num != currentNode.num) {
+            if (currentNode.num > 1)
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt]:
```
val coroutineStackHeader = if (currentNode.num > 1) {
 ...
} else {
 ...
}
```

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 67]
```diff
@@ -1,64 +1,145 @@
...
 
     init {
-        layout = BorderLayout()
+        layout = BoxLayout(this, BoxLayout.Y_AXIS)
         emptyText.text = CoroutineStacksBundle.message("no.java.debug.process.is.running")
+        val currentSession = XDebuggerManager.getInstance(project).currentSession
+        if (currentSession != null) {
+            val javaDebugProcess = currentSession.debugProcess as? JavaDebugProcess
+            val currentProcess = javaDebugProcess?.debuggerSession?.process
+            emptyText.component.isVisible = false
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: What if current session is not null, but the `javaDebugProcess` variable is null, or `currentProcess` is null? This way we will hide the `No java debug process is currently running` message, when we actually shouldn't have done this. This situation can happen if, for example, a user starts a python debugging session in a Java project.

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 68]
```diff
@@ -1,64 +1,145 @@
...
+        val coroutineInfoCache = CoroutineDebugProbesProxy(suspendContextImpl).dumpCoroutines()
+        val coroutineInfoDataList = coroutineInfoCache.cache
+        val dispatcherToCoroutineDataList = mutableMapOf<String, MutableList<CoroutineInfoData>>()
+        for (info in coroutineInfoDataList) {
+            val dispatcher = info.descriptor.dispatcher ?: continue
+            dispatcherToCoroutineDataList.computeIfAbsent(dispatcher) { mutableListOf() }.add(info)
+        }
+
+        val dispatcherLabel = JLabel(CoroutineStacksBundle.message("select.dispatcher"))
+        val coroutineStacksWindowHeader = Box.createHorizontalBox()
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: `coroutineStacksPanelHeader`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 69]
```diff
@@ -1,64 +1,145 @@
...
+        coroutineDataList: MutableList<CoroutineInfoData>,
+        suspendContextImpl: SuspendContextImpl
+    ) {
+        suspendContextImpl.debugProcess.managerThread.invoke(object : DebuggerCommandImpl() {
+            override fun action() {
+                val root = Node()
+                val coroutineStackForest = suspendContextImpl.buildCoroutineStackForest(
+                    root,
+                    coroutineDataList
+                ) ?: run {
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: I think here it will look better to use plain `if` instead of the elvis operator:
```
if (coroutineStackForest == null) {
...
}
```

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt [hunk 70]
```diff
@@ -0,0 +1,173 @@
...
+private fun SuspendContextImpl.buildStackFrameGraph(
+    coroutineDataList: List<CoroutineInfoData>,
+    rootValue: Node
+): String {
+    var lastRunningStackFrame = ""
+
+    coroutineDataList.forEach { coroutineData ->
+        var currentNode = rootValue
+
+        val coroutineFrameItemLists = CoroutineFrameBuilder.build(coroutineData, this)
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt]: `val coroutineFrameItemLists = CoroutineFrameBuilder.build(coroutineData, this) ?: return@forEach`

**Review by nikita-nazarov — CHANGES_REQUESTED** [review]

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/Constants.kt [hunk 71]
```diff
@@ -0,0 +1,11 @@
+package com.nikitanazarov.coroutinestacks
+
+class Constants {
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/Constants.kt]: Let's remove this class and introduce corresponding constants closer to their use site. I will add more comments on that in this review.

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 72]
```diff
@@ -1,64 +1,147 @@
...
-        with(graph) {
-            val parent = defaultParent
-            model.beginUpdate()
-            try {
-                val v1 = insertVertex(parent, null, "Hello,", 20.0, 20.0, 80.0, 30.0)
-                val v2 = insertVertex(parent, null, "World!", 200.0, 150.0, 80.0, 30.0)
-                insertEdge(parent, null, "", v1, v2)
-            } finally {
-                model.endUpdate()
+    private fun panelBuilderListener() = object : DebugProcessListener {
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]:
```
private val panelBuilderListener = object : DebugProcessListener { ...
```
And it should be declared in top of the class.

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 73]
```diff
@@ -1,64 +1,147 @@
...
+        suspendContextImpl: SuspendContextImpl
+    ) {
+        suspendContextImpl.debugProcess.managerThread.invoke(object : DebuggerCommandImpl() {
+            override fun action() {
+                val root = Node()
+                val coroutineStackForest = suspendContextImpl.buildCoroutineStackForest(
+                    root,
+                    coroutineDataList
+                )
+                if (coroutineStackForest == null)
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: `if (coroutineStackForest == null) {`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt [hunk 74]
```diff
@@ -0,0 +1,132 @@
...
+import javax.swing.border.LineBorder
+
+class CoroutineFramesList(
+    suspendContext: SuspendContextImpl,
+    trace: CoroutineTrace,
+    lastRunningStackFrame: String
+) : JBList<String>() {
+    companion object {
+        private val itemBorder = BorderFactory.createMatteBorder(0, 0, 1, 0, JBColor.GRAY)
+        private val leftPaddingBorder: Border = JBUI.Borders.emptyLeft(Constants.leftPaddingForBorder)
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt]: The Constants.leftPaddingForBorder value can be inlined here.

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt [hunk 75]
```diff
@@ -0,0 +1,132 @@
...
+                if (executionStack != null) {
+                    session.setCurrentStackFrame(executionStack, stackFrame, false)
+                }
+            }
+        }
+    }
+
+    private fun createRoundedBorder(color: JBColor): Border {
+        val cornerRadius = Constants.cornerRadius
+        val borderThickness = Constants.borderThickness
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt]: These variables are not needed, you can inline their values on the use sites. And let's move Constants.cornerRadius and Constants.borderThickness to CoroutineFramesList

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 76]
```diff
@@ -1,64 +1,147 @@
...
+
+        dispatcherDropdownMenu.addActionListener {
+            val selectedDispatcher = dispatcherDropdownMenu.selectedItem as? String
+            val coroutineDataList = dispatcherToCoroutineDataList[selectedDispatcher]
+            if (!coroutineDataList.isNullOrEmpty()) {
+                updateCoroutineStackForest(coroutineDataList, suspendContextImpl)
+            }
+        }
+
+        val comboBoxSize = Dimension(Constants.comboBoxHeight, Constants.comboBoxWidth)
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Let's create a constant in a companion object of this class. 
```
val comboBoxSize = Dimension(150, 25)
```
And let's remove Constnants.comboBoxHeight and width

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt [hunk 77]
```diff
@@ -0,0 +1,132 @@
...
+                    if (suspendContext.activeExecutionStack != null && frame != null) {
+                        suspendContext.setCurrentStackFrame(suspendContext.activeExecutionStack, frame)
+                    }
+                }
+            }
+        })
+    }
+
+    // Copied from org.jetbrains.kotlin.idea.debugger.coroutine.view.CoroutineSelectedNodeListener#setCurrentStackFrame
+    private fun SuspendContextImpl.setCurrentStackFrame(executionStack: XExecutionStack?, stackFrame: XStackFrame) {
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt]: Let's move this function out of the class body, as it doesn't use any class fields or methods

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt [hunk 78]
```diff
@@ -0,0 +1,132 @@
...
+
+                return renderer
+            }
+        }
+
+        addMouseListener(object : MouseAdapter() {
+            override fun mouseClicked(e: MouseEvent?) {
+                val list = e?.source as? JBList<*> ?: return
+                val index = list.locationToIndex(e.point).takeIf { it > 0 } ?: return
+                val stackFrameItem = trace.stackFrameItems[index - 1]
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt]: `val stackFrameItem = trace.stackFrameItems[index - 1] ?: return`

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt (hunk 45 above)
Comment (nikita-nazarov) [reply src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Why you have marked this conversation as resolved while it is not resolved? This line contains a bug. The `javax.swing.JComboBox#getSelectedItem` function is marked as `@Nullable`, which means it can return null. So if selectedItem is null, strong casting it to String will throw an exception!

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt [hunk 79]
```diff
@@ -0,0 +1,173 @@
...
+    while (stack.isNotEmpty()) {
+        val (currentNode, currentLevel) = stack.pop()
+        val parent = if (parentStack.isNotEmpty()) parentStack.pop() else null
+        val coroutineStackHeader = if (currentNode.num > 1) {
+            CoroutineStacksBundle.message("number.of.coroutines", currentNode.num)
+        } else {
+            CoroutineStacksBundle.message("number.of.coroutine")
+        }
+
+            if (parent != null && parent.num != currentNode.num) {
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt]: This code block has incorrect indentation

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt [hunk 80]
```diff
@@ -0,0 +1,132 @@
...
+
+                stackFrameItem?.let { frameItem ->
+                    val frame = frameItem.createFrame(debugProcess)
+
+                    if (suspendContext.activeExecutionStack != null && frame != null) {
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt]: Let's extract `suspendContext.activeExecutionStack` to a variable

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt [hunk 81]
```diff
@@ -0,0 +1,132 @@
...
+        })
+    }
+
+    // Copied from org.jetbrains.kotlin.idea.debugger.coroutine.view.CoroutineSelectedNodeListener#setCurrentStackFrame
+    private fun SuspendContextImpl.setCurrentStackFrame(executionStack: XExecutionStack?, stackFrame: XStackFrame) {
+        val fileToNavigate = stackFrame.sourcePosition?.file ?: return
+        val session = debugProcess.session.xDebugSession ?: return
+        if (!ClsClassFinder.isKotlinInternalCompiledFile(fileToNavigate)) {
+            ApplicationManager.getApplication().invokeLater {
+                if (executionStack != null) {
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt]: So if executionStack is null, looks like you still launched a UI thread just to check this condition, while we could have checked it on the call site.

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt (hunk 77 above)
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt]: Let's make executionStack non nullable and check if it is null on the call site.

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt [hunk 82]
```diff
@@ -0,0 +1,173 @@
...
+import java.util.*
+
+data class Node(
+    val stackFrameItem: CoroutineStackFrameItem? = null,
+    var num: Int = 0, // Represents how many coroutines have this frame in their stack trace
+    val children: MutableMap<Location, Node> = mutableMapOf(),
+    var coroutinesActive: String = ""
+)
+
+data class CoroutineTrace(val stackFrameItems: MutableList<CoroutineStackFrameItem?>,
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt]: Let's place parameters the same way they are placed in Node

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt [hunk 83]
```diff
@@ -0,0 +1,132 @@
...
+                    session.setCurrentStackFrame(executionStack, stackFrame, false)
+                }
+            }
+        }
+    }
+
+    private fun createRoundedBorder(color: JBColor): Border {
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt]: Actually we don't need this function, we can replace it with plain anonymous object like this:
```
val borderColor = if (...) BLUE else GRAY
border = object : LineBorder(...) { ... } // Use borderColor here
```

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt [hunk 84]
```diff
@@ -1,64 +1,147 @@
...
+import org.jetbrains.kotlin.idea.debugger.coroutine.data.CoroutineInfoData
+import org.jetbrains.kotlin.idea.debugger.coroutine.data.State
 import org.jetbrains.kotlin.idea.debugger.coroutine.proxy.CoroutineDebugProbesProxy
-import java.awt.BorderLayout
-import javax.swing.JComponent
-import javax.swing.SwingConstants
+import java.awt.*
+import javax.swing.*
 
 class CoroutineStacksPanel(project: Project) : JBPanelWithEmptyText() {
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineStacksPanel.kt]: Let's move this class to the ui package

**Review by nikita-nazarov — CHANGES_REQUESTED** [review]

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt [hunk 85]
```diff
@@ -0,0 +1,128 @@
...
+    }
+
+    init {
+        val debugProcess = suspendContext.debugProcess
+
+        val data = mutableListOf<String>()
+        data.add(trace.header)
+        val renderer = SimpleColoredTextIconPresentationRenderer()
+        data.addAll(trace.stackFrameItems.map {
+            renderer.render(it!!.location).simpleString()
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt]: Let's just add an empty string if we accidentally get a null. Throwing exceptions from a constructor is a very bad pattern!

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineStacksPanel.kt [hunk 86]
```diff
@@ -0,0 +1,168 @@
...
+            maximumSize = comboBoxSize
+            minimumSize = comboBoxSize
+        }
+        coroutineStacksPanelHeader.add(dispatcherLabel)
+        coroutineStacksPanelHeader.add(dispatcherDropdownMenu)
+        val breakpointLocation = suspendContextImpl.location
+
+        dispatcherToCoroutineDataList.forEach { (dispatcher, coroutineDataList) ->
+            coroutineDataList.forEach { data ->
+                if (data.descriptor.state == State.RUNNING && data.stackTrace.first().location == breakpointLocation) {
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineStacksPanel.kt]: If `data.stackTrace` is empty we will get an exception here. It is better to use firstOrNull().

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineStacksPanel.kt [hunk 87]
```diff
@@ -0,0 +1,168 @@
...
+                runInEdt {
+                    forest.removeAll()
+                    forest.add(coroutineStackForest)
+                    updateUI()
+                }
+            }
+        })
+    }
+
+    companion object {
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineStacksPanel.kt]: Let's move the companion object to the top of the class.

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineStacksPanel.kt [hunk 88]
```diff
@@ -0,0 +1,168 @@
...
+        const val comboBoxHeight = 25
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineStacksPanel.kt]: Let's name these constants with capital letters.

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt [hunk 89]
```diff
@@ -0,0 +1,128 @@
...
+
+class CoroutineFramesList(
+    suspendContext: SuspendContextImpl,
+    trace: CoroutineTrace
+) : JBList<String>() {
+    companion object {
+        private val itemBorder = BorderFactory.createMatteBorder(0, 0, 1, 0, JBColor.GRAY)
+        private val leftPaddingBorder: Border = JBUI.Borders.emptyLeft(3)
+        private val compoundBorder = BorderFactory.createCompoundBorder(itemBorder, leftPaddingBorder)
+        private const val cornerRadius = 10
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt]: Let's name the last two constants with capital letters like CORNER_RADIUS

**Review by nikita-nazarov — CHANGES_REQUESTED** [review]
The code is much cleaner now! Great job!

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineStacksPanel.kt [hunk 90]
```diff
@@ -0,0 +1,217 @@
...
+        init {
+            addActionListener {
+                val selectedDispatcher = selectedItem as? String
+                val coroutineDataList = dispatcherToCoroutineDataList[selectedDispatcher]
+                if (!coroutineDataList.isNullOrEmpty()) {
+                    updateCoroutineStackForest(coroutineDataList, suspendContextImpl)
+                }
+            }
+
+            val comboBoxSize = Dimension(COMBO_BOX_WIDTH, COMBO_BOX_HEIGHT)
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineStacksPanel.kt]: Since we have a separate class for dispatcher drop down menu, let's add this to companion object in this class:
```
companion object {
   val dispatcherSelectionMenuSize = Dimension(200, 25)
}
```

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineStacksPanel.kt [hunk 91]
```diff
@@ -0,0 +1,217 @@
...
+            add(dispatcherLabel)
+            add(dispatcherDropdownMenu)
+            add(createHorizontalGlue())
+            add(libraryFrameToggle)
+        }
+    }
+
+    inner class DispatcherDropdownMenu (
+        suspendContextImpl: SuspendContextImpl,
+        dispatcherToCoroutineDataList: Map<String?, List<CoroutineInfoData>>
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineStacksPanel.kt]: It is a little weird to have a map with nullable keys, can we just make it Map<String, List<CoroutineInfoData>>?

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineStacksPanel.kt [hunk 92]
```diff
@@ -0,0 +1,217 @@
...
+
+            add(createHorizontalGlue())
+            add(dispatcherLabel)
+            add(dispatcherDropdownMenu)
+            add(createHorizontalGlue())
+            add(libraryFrameToggle)
+        }
+    }
+
+    inner class DispatcherDropdownMenu (
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineStacksPanel.kt]: Extra space after DispatcherDropdownMenu

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt [hunk 93]
```diff
@@ -0,0 +1,128 @@
...
+        private const val BORDER_THICKNESS = 1
+    }
+
+    init {
+        val debugProcess = suspendContext.debugProcess
+
+        val data = mutableListOf<String>()
+        data.add(trace.header)
+        val renderer = SimpleColoredTextIconPresentationRenderer()
+        data.addAll(trace.stackFrameItems.map { item ->
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt]: To not visit null items we can use mapNotNull

**Review by nikita-nazarov — CHANGES_REQUESTED** [review]
Hi Raehat! Here are my comments. The idea to create separate classes for UI components was great!

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt [hunk 94]
```diff
@@ -40,8 +40,10 @@ class CoroutineFramesList(
         val data = mutableListOf<String>()
         data.add(trace.header)
         val renderer = SimpleColoredTextIconPresentationRenderer()
-        data.addAll(trace.stackFrameItems.map { item ->
-            item?.let { renderer.render(it.location).simpleString() } ?: ""
+        data.addAll(trace.stackFrameItems.mapNotNull { item ->
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineFramesList.kt]:
```
        data.addAll(trace.stackFrameItems.mapNotNull { 
            it ?: return@mapNotNull null
            renderer.render(it.location).simpleString()
        })
```

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineStacksPanel.kt [hunk 95]
```diff
@@ -98,7 +97,10 @@ class CoroutineStacksPanel(project: Project) : JBPanelWithEmptyText() {
         }
 
         val coroutineInfoDataList = coroutineInfoCache.cache
-        val dispatcherToCoroutineDataList = coroutineInfoDataList.groupBy { it.descriptor.dispatcher }
+        val dispatcherToCoroutineDataList = coroutineInfoDataList
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/ui/CoroutineStacksPanel.kt]:
```
        val dispatcherToCoroutineDataList = mutableMapOf<String, MutableList<CoroutineInfoData>>()
        for (data in coroutineInfoDataList) {
            data.descriptor.dispatcher?.let {
                dispatcherToCoroutineDataList.getOrPut(it) { mutableListOf() }.add(data)
            }
        }

```
This way we won't have an empty key in our map and just skip coroutines which have a dispatcher equal to null

File: src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt [hunk 96]
```diff
@@ -0,0 +1,175 @@
...
+        try {
+            coroutineFrameItemLists = CoroutineFrameBuilder.build(coroutineData, this) ?: return@forEach
+        } catch (e : Exception) {
+            return@forEach
+        }
+        coroutineFrameItemLists.frames.reversed().forEach { stackFrame ->
+            val xStackFrame = stackFrame.createFrame(debugProcess)
+            val isLibraryFrame = (xStackFrame as JVMStackFrameInfoProvider).isInLibraryContent
+            if (isLibraryFrame && CoroutineStackPanelData.areLibraryFramesAllowed.not())
+                return@forEach
```
Comment (nikita-nazarov) [inline src/main/kotlin/com/nikitanazarov/coroutinestacks/CoroutineTraceForestBuilder.kt]: The warning here says "There is more than one label with such a name in this scope"

**Review by nikita-nazarov — CHANGES_REQUESTED** [review]

**Review by nikita-nazarov — APPROVED** [review]
